# Generated by Django 5.1.2 on 2024-12-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_bio",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
