# Generated by Django 5.1.2 on 2024-10-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("speed", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
