# Generated by Django 5.1.2 on 2024-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recepe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recepie_name", models.CharField(max_length=100)),
                ("recepie_description", models.TextField()),
                ("recepie_image", models.ImageField(upload_to="recepie")),
            ],
        ),
    ]
