# Generated by Django 5.1.2 on 2024-10-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Recepe",
            new_name="Recepie",
        ),
    ]
