# Generated by Django 5.1.2 on 2024-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_reportcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_report_card_generation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
